package wj.ssm.po;

public class Student {
    private Integer stuid;

    private String name;

    private Integer age;

    private Integer tName;

    private Integer cName;

    private String image;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuId
     *
     * @return the value of student.stuId
     *
     * @mbggenerated Sun Jul 02 10:29:57 CST 2017
     */
    public Integer getStuid() {
        return stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuId
     *
     * @param stuid the value for student.stuId
     *
     * @mbggenerated Sun Jul 02 10:29:57 CST 2017
     */
    public void setStuid(Integer stuid) {
        this.stuid = stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     *
     * @mbggenerated Sun Jul 02 10:29:57 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     *
     * @mbggenerated Sun Jul 02 10:29:57 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.age
     *
     * @return the value of student.age
     *
     * @mbggenerated Sun Jul 02 10:29:57 CST 2017
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.age
     *
     * @param age the value for student.age
     *
     * @mbggenerated Sun Jul 02 10:29:57 CST 2017
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.t_name
     *
     * @return the value of student.t_name
     *
     * @mbggenerated Sun Jul 02 10:29:57 CST 2017
     */
    public Integer gettName() {
        return tName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.t_name
     *
     * @param tName the value for student.t_name
     *
     * @mbggenerated Sun Jul 02 10:29:57 CST 2017
     */
    public void settName(Integer tName) {
        this.tName = tName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.c_name
     *
     * @return the value of student.c_name
     *
     * @mbggenerated Sun Jul 02 10:29:57 CST 2017
     */
    public Integer getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.c_name
     *
     * @param cName the value for student.c_name
     *
     * @mbggenerated Sun Jul 02 10:29:57 CST 2017
     */
    public void setcName(Integer cName) {
        this.cName = cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.image
     *
     * @return the value of student.image
     *
     * @mbggenerated Sun Jul 02 10:29:57 CST 2017
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.image
     *
     * @param image the value for student.image
     *
     * @mbggenerated Sun Jul 02 10:29:57 CST 2017
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }
}